# Generated by Django 5.2 on 2026-05-10 23:27

import django.core.validators
import ongs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('slogan', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to=ongs.models.generate_uploaded_img_name, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Ong',
                'verbose_name_plural': 'Ongs',
                'db_table': 'ong',
                'ordering': ['name'],
            },
        ),
    ]
