# Generated by Django 5.2 on 2026-05-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
