# Generated by Django 5.2 on 2026-05-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0002_ongs_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongs',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
