# Generated by Django 5.2 on 2026-05-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0003_ongs_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongs',
            name='website',
        ),
        migrations.AddField(
            model_name='ongs',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
